repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

  # - isort needs seed-isort-config to work as expected
  -   repo: https://github.com/asottile/seed-isort-config
      rev: v2.1.1
      hooks:
        - id: seed-isort-config
  # - to work along black .isort.cfg needs some work
  -   repo: https://github.com/timothycrosley/isort
      rev: 4.3.21-2
      hooks:
        -   id: isort

  -   repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
        - id: black

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.2
      hooks:
        # add warnings you wish to ignore to flake8 config file
        - id: flake8

  -   repo: https://github.com/jazzband/pip-tools
      rev: 5.2.0
      hooks:
        - id: pip-compile
          files: requirements.in
          args: [--quiet, --output-file=requirements.txt, requirements.in]

  -   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
        - id: dockerfilelint

  -   repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
        - id: bandit
          # add warnings you wish to ignore to bandits config file
          args: [-c=.banditrc.yml]

  -   repo: https://github.com/asottile/dead
      rev: v1.3.0
      hooks:
        - id: dead

  # ==============================================================
  # - The following hooks have to be installed manually.
  # - `swagger-markdown` expects a file `openapi.yml` to be present in your projects main directory.
  # ==============================================================

  #-   repo: local
  #    hooks:
  #      -   id: run-tests
  #          name: Run Tests
  #          entry: pytest
  #          language: system
  #          types: [python]
  #          pass_filenames: false
  #          verbose: true

  #      -   id: generate-api-doc
  #          name: Generate API Documentation
  #          entry: swagger-markdown -i ./openapi.yml -o api-documentation.md
  #          language: system
  #          files: swagger.yml
  #          pass_filenames: false

  #      -   id: ansible-lint
  #          name: Ansible-lint
  #          description: This hook runs ansible-lint.
  #          entry: ansible-lint --force-color
  #          language: system
  #          pass_filenames: false
  #          always_run: true
